### ISSUE TITLE
Use volume/window button control clover boot menu

### ISSUE THREAD

**Issue by Rassyan** [laelsirus/Dell-Latitude-5290-2-in-1-UHD620-iGPU-CLOVER#4]
Hi! laelsirus. I'm your big fan! I appreciate you huge effort on this!
I wonder that is there any way to map VOLUME_UP/VOLUME_DOWN/WIINDOW button to up/down/enter  keyboard button. Thus we can control it at the clover boot menu stage when using tablet mode without keyboard.
Could you tell me how to do it? Thank you!
![image](https://user-images.githubusercontent.com/26055883/77140804-b8300100-6ab5-11ea-80d6-066673fceeac.png)

**Comment by laelsirus** [comment]
I know exactly what you want, and I had researched to make it possible before.
To make it possible, it requires advanced programming development that links the clover bootloader with the efi driver.
Because it has to make changes that something not previously developed in the clover bootloader space. (For example, touch screen support in the clover bootloader area)
I think it is a quick way to solve this by asking enough questions to the clover bootloader developer.
If this is solved, I will be very happy too.

Thank you for using my build and if you have any issues not in the readme, please leave a problem report.

**Comment by Rassyan** [comment]
Ok, I get it now, thanks！
And I noticed in your readme that you have mapped window button to Option Key.
How did you do that?

**Comment by laelsirus** [comment]
That works with voodoops2controller.kext.
I did nothing :)

**Comment by Rassyan** [comment]
Well, get it.
I'll as you said, give it a try to solve this issue. Maybe impossible to achieve.

**Comment by laelsirus** [comment]
Hope you have some good news :)
